version: '3'

services:
  rabbitmq:
    container_name: rabbitMQ
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: unless-stopped
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: 5m
    volumes:
      - rabbitMQVolume:/var/lib/rabbitmq/mnesia/

  redis:
    container_name: redis-stackanother
    image: 'redis/redis-stack:latest'
    ports:
      - '6379:6379'
      - '8001:8001'
    restart: unless-stopped
    depends_on:
      - rabbitmq
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: 5m

volumes:
  rabbitMQVolume: